# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/trifenix-main.csproj'
    feedsToUse: 'select'
    vstsFeed: '0e468e6a-c444-43d7-95e1-61f36d80dbd2/02e7cc4e-a132-4f42-bf59-4cf10b26ee43'

